export const SHOW_PLANET_LOADER = 'SHOW_PLANET_LOADER';
export const HIDE_PLANET_LOADER = 'HIDE_PLANET_LOADER';
export const SHOW_PEOPLE_LOADER = 'SHOW_PEOPLE_LOADER';
export const HIDE_PEOPLE_LOADER = 'HIDE_PEOPLE_LOADER';

export const FETCH_PEOPLE_DATA = 'FETCH_PEOPLE_DATA';
export const FETCH_PLANET_DATA = 'FETCH_PLANET_DATA';

export const SET_SEARCH_RESPONSE = 'SET_SEARCH_RESPONSE';
export const CLEAR_SEARCH_RESPONSE = 'CLEAR_SEARCH_RESPONSE';

export const SHOW_SEARCH_ERROR = 'SHOW_SEARCH_ERROR';
export const HIDE_SEARCH_ERROR = 'HIDE_SEARCH_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const SHOW_PEOPLE_ERROR = 'SHOW_PEOPLE_ERROR';
export const HIDE_PEOPLE_ERROR = 'HIDE_PEOPLE_ERROR';

export const SHOW_PLANET_ERROR = 'SHOW_PLANET_ERROR';
export const HIDE_PLANET_ERROR = 'HIDE_PLANET_ERROR';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGE = 'SET_TOTAL_PAGE';
