export const FETCH_PEOPLE_DATA = 'FETCH_PEOPLE_DATA';
export const FETCH_PLANET_DATA = 'FETCH_PLANET_DATA';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SHOW_PEOPLE_ERROR = 'SHOW_PEOPLE_ERROR';
export const HIDE_PEOPLE_ERROR = 'HIDE_PEOPLE_ERROR';
export const SHOW_PLANET_ERROR = 'SHOW_PLANET_ERROR';
export const HIDE_PLANET_ERROR = 'HIDE_PLANET_ERROR';